'use strict';

/**
 * Generates .env.example with required secrets based on
 * the selected browser targets and publish mode.
 */
function generateExtensionEnvExample(config) {
  const { browserTargets = ['chrome'], publishMode } = config;
  const autoPublish = publishMode === 'auto-publish';

  const sections = [];

  sections.push({
    title: 'Extension',
    vars: [
      { key: 'NODE_ENV', value: 'production', comment: 'production | development' },
    ],
  });

  if (autoPublish && browserTargets.includes('chrome')) {
    sections.push({
      title: 'Chrome Web Store (GitHub Actions Secrets)',
      vars: [
        { key: 'CHROME_EXTENSION_ID', value: '', comment: 'Chrome Web Store → Developer Dashboard → your item ID' },
        { key: 'CHROME_CLIENT_ID', value: '', comment: 'Google Cloud Console → OAuth client ID (Desktop app)' },
        { key: 'CHROME_CLIENT_SECRET', value: '', comment: 'Google Cloud Console → OAuth client secret' },
        { key: 'CHROME_REFRESH_TOKEN', value: '', comment: 'Generated via OAuth playground, see PUBLISHING_NOTES.md' },
      ],
    });
  }

  if (autoPublish && browserTargets.includes('firefox')) {
    sections.push({
      title: 'Firefox Add-ons (GitHub Actions Secrets)',
      vars: [
        { key: 'FIREFOX_JWT_ISSUER', value: '', comment: 'addons.mozilla.org → Manage API Keys → JWT issuer' },
        { key: 'FIREFOX_JWT_SECRET', value: '', comment: 'addons.mozilla.org → Manage API Keys → JWT secret' },
      ],
    });
  }

  if (autoPublish && browserTargets.includes('edge')) {
    sections.push({
      title: 'Edge Add-ons (GitHub Actions Secrets)',
      vars: [
        { key: 'EDGE_PRODUCT_ID', value: '', comment: 'Partner Center → Edge Add-ons → Product ID' },
        { key: 'EDGE_CLIENT_ID', value: '', comment: 'Partner Center → Azure AD App Registration' },
        { key: 'EDGE_CLIENT_SECRET', value: '', comment: 'Partner Center → Azure AD App Registration' },
        { key: 'EDGE_ACCESS_TOKEN_URL', value: '', comment: 'https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token' },
      ],
    });
  }

  sections.push({
    title: 'Optional — Notifications & monitoring',
    vars: [
      { key: 'SLACK_WEBHOOK_URL', value: '', comment: 'Optional: Slack incoming webhook for release notifications' },
      { key: 'SENTRY_DSN', value: '', comment: 'Optional: Sentry error tracking DSN' },
    ],
  });

  const lines = [
    `# .env.example`,
    `# Generated by CI/CD Pipeline Generator — Chrome Extension`,
    `# Copy this file to .env and fill in the values`,
    `# NEVER commit .env to version control`,
    ``,
  ];

  for (const section of sections) {
    lines.push(`# ── ${section.title} ${'─'.repeat(Math.max(0, 60 - section.title.length))}`);
    for (const v of section.vars) {
      if (v.comment) {
        lines.push(`# ${v.comment}`);
      }
      lines.push(`${v.key}=${v.value}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

module.exports = { generateExtensionEnvExample };
