'use strict';

const { generateExtensionCI } = require('./templates/ci');
const { generatePackageRelease } = require('./templates/package-release');
const { generatePublishStore } = require('./templates/publish-store');
const { generateExtensionEnvExample } = require('./templates/env-example');

/**
 * Main entry point for Chrome Extension CI/CD generation.
 * @param {object} config
 * @param {string} config.extensionFramework - vanilla | typescript | react | vue
 * @param {string} config.nodeVersion        - Node.js version used in generated workflows
 * @param {string} config.packageManager     - npm | yarn | pnpm
 * @param {string} config.buildTool          - none | webpack | vite | parcel
 * @param {string[]} config.browserTargets   - chrome | firefox | edge (chrome always included)
 * @param {string} config.productionBranch   - name of the branch that triggers build & release (default: main)
 * @param {string[]} config.extraBranches    - additional branch names that should also run CI
 * @param {string[]} config.checks           - lint | typecheck | test | build | validate-manifest
 * @param {string} config.publishMode        - zip-only | auto-publish
 * @returns {object} Map of relative file paths → file content strings
 */
function generateExtensionWorkflows(config) {
  const normalised = {
    extensionFramework: config.extensionFramework || 'vanilla',
    nodeVersion: config.nodeVersion || '24',
    packageManager: config.packageManager || 'npm',
    buildTool: config.buildTool || 'none',
    browserTargets: Array.isArray(config.browserTargets) && config.browserTargets.length > 0
      ? Array.from(new Set(['chrome', ...config.browserTargets]))
      : ['chrome'],
    productionBranch: config.productionBranch || 'main',
    extraBranches: Array.isArray(config.extraBranches) ? config.extraBranches : [],
    checks: Array.isArray(config.checks) ? config.checks : [],
    publishMode: config.publishMode === 'auto-publish' ? 'auto-publish' : 'zip-only',
  };

  const files = {};

  files['.github/workflows/ci.yml'] = generateExtensionCI(normalised);
  files['.github/workflows/package-release.yml'] = generatePackageRelease(normalised);

  if (normalised.publishMode === 'auto-publish') {
    files['.github/workflows/publish-store.yml'] = generatePublishStore(normalised);
  }

  files['.env.example'] = generateExtensionEnvExample(normalised);
  files['PUBLISHING_NOTES.md'] = generatePublishingNotes(normalised);

  return files;
}

function generatePublishingNotes(config) {
  const { extensionFramework, browserTargets, productionBranch, extraBranches, checks, publishMode, buildTool } = config;

  const frameworkNames = {
    vanilla: 'Vanilla JavaScript',
    typescript: 'TypeScript',
    react: 'React',
    vue: 'Vue',
  };

  const browserNames = { chrome: 'Chrome Web Store', firefox: 'Firefox Add-ons', edge: 'Edge Add-ons' };

  const branchFlowDesc = [...extraBranches, productionBranch].map((b) => `\`${b}\``).join(' → ');

  const checksDesc = checks.length > 0
    ? checks.map(c => ({
        lint: '`npm run lint` — ESLint',
        typecheck: '`npm run typecheck` — TypeScript type checking',
        test: 'Unit tests',
        build: '`npm run build` — Bundles the extension',
        'validate-manifest': 'Validates `manifest.json` (Manifest V3, required fields)',
      }[c] || c)).join('\n- ')
    : 'None selected';

  return `# Chrome Extension — Publishing Notes

Generated by [CI/CD Pipeline Generator](https://github.com/your-org/cicd-pipeline-generator)

## Project Configuration

| Setting | Value |
|---------|-------|
| Framework | ${frameworkNames[extensionFramework] || extensionFramework} |
| Build tool | ${buildTool === 'none' ? 'None (plain files)' : buildTool} |
| Browser targets | ${browserTargets.map(b => browserNames[b] || b).join(', ')} |
| Branch flow | ${branchFlowDesc} |
| Publish mode | ${publishMode === 'auto-publish' ? 'Auto-publish to store(s) on version tag' : 'Build & zip only (manual upload)'} |

## Checks Included

- ${checksDesc}

## Workflow Files

| File | Trigger | Purpose |
|------|---------|---------|
| \`.github/workflows/ci.yml\` | Every PR / push | Lint, typecheck, test, build, validate manifest |
| \`.github/workflows/package-release.yml\` | Push to \`${productionBranch}\` | Build, zip per browser target, create GitHub Release with assets |
${publishMode === 'auto-publish' ? `| \`.github/workflows/publish-store.yml\` | Push tag \`v*.*.*\` | Auto-publish to ${browserTargets.map(b => browserNames[b] || b).join(', ')} |` : ''}

## Required GitHub Secrets

${getSecretsTable(browserTargets, publishMode)}

## Store Setup

${browserTargets.map((b) => getStoreNotes(b)).join('\n\n')}

## Release Checklist

- [ ] Bump \`version\` in \`manifest.json\` and \`package.json\` before merging to \`${productionBranch}\`
- [ ] Merge to \`${productionBranch}\` — this builds, zips, and creates a GitHub Release
- [ ] ${publishMode === 'auto-publish' ? 'Push a version tag (e.g. `git tag v1.2.0 && git push origin v1.2.0`) to trigger the store publish workflow' : 'Download the zip from the GitHub Release and upload it manually to each store'}
- [ ] Verify the listing on each store dashboard after publishing (review can take hours to days)
`;
}

function getSecretsTable(browserTargets, publishMode) {
  if (publishMode !== 'auto-publish') {
    return 'None required — this project only builds and zips the extension; store uploads are manual.';
  }

  const rows = [];

  if (browserTargets.includes('chrome')) {
    rows.push(
      ['`CHROME_EXTENSION_ID`', 'Item ID of the extension', 'Chrome Web Store Developer Dashboard'],
      ['`CHROME_CLIENT_ID`', 'OAuth client ID', 'Google Cloud Console → Credentials'],
      ['`CHROME_CLIENT_SECRET`', 'OAuth client secret', 'Google Cloud Console → Credentials'],
      ['`CHROME_REFRESH_TOKEN`', 'OAuth refresh token', 'Generated once via OAuth consent flow'],
    );
  }
  if (browserTargets.includes('firefox')) {
    rows.push(
      ['`FIREFOX_JWT_ISSUER`', 'AMO API key (JWT issuer)', 'addons.mozilla.org → Manage API Keys'],
      ['`FIREFOX_JWT_SECRET`', 'AMO API secret (JWT secret)', 'addons.mozilla.org → Manage API Keys'],
    );
  }
  if (browserTargets.includes('edge')) {
    rows.push(
      ['`EDGE_PRODUCT_ID`', 'Edge Add-ons product ID', 'Partner Center → Edge Add-ons'],
      ['`EDGE_CLIENT_ID`', 'Azure AD app client ID', 'Partner Center → Azure AD App Registration'],
      ['`EDGE_CLIENT_SECRET`', 'Azure AD app client secret', 'Partner Center → Azure AD App Registration'],
      ['`EDGE_ACCESS_TOKEN_URL`', 'Azure AD token endpoint', 'https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token'],
    );
  }

  const header = '| Secret | Description | Where to find it |\n|--------|-------------|------------------|';
  const body = rows.map(([secret, desc, where]) => `| ${secret} | ${desc} | ${where} |`).join('\n');
  return `${header}\n${body}`;
}

function getStoreNotes(target) {
  switch (target) {
    case 'chrome':
      return `### Chrome Web Store

- Register as a Chrome Web Store developer (one-time $5 fee): https://chrome.google.com/webstore/devconsole
- Create the item once manually, upload an initial build, and note the item ID (\`CHROME_EXTENSION_ID\`)
- Create OAuth credentials in Google Cloud Console (Desktop app type) for \`CHROME_CLIENT_ID\` / \`CHROME_CLIENT_SECRET\`
- Generate a refresh token once via the OAuth consent screen (see \`chrome-webstore-upload-cli\` docs) for \`CHROME_REFRESH_TOKEN\``;

    case 'firefox':
      return `### Firefox Add-ons (AMO)

- Create/verify your listing at https://addons.mozilla.org/developers/
- Generate API credentials at https://addons.mozilla.org/developers/addon/api/key/
- \`web-ext sign\` uploads and signs the build automatically; review is required before it goes live`;

    case 'edge':
      return `### Microsoft Edge Add-ons

- Register in Partner Center: https://partner.microsoft.com/dashboard/microsoftedge
- Create an Azure AD app registration for API access and note the client ID/secret
- Find your product ID on the Edge Add-ons dashboard for your listing`;

    default:
      return '';
  }
}

module.exports = { generateExtensionWorkflows };
